version: '2'

services:
  cms:
    image: drupal:8.8.2
    ports:
      - '8080:80'
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
  postgres-db:
    image: postgres:12.1
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: druser
      POSTGRES_PASSWORD: resurd

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
